if [[ -e $HOME/var/env/config/local/vars.zsh ]] ; then
  source $HOME/var/env/config/local/vars.zsh
fi

# load path settings first
export DOTFILES=$HOME/var/env
export PATH=$PATH:$DOTFILES/bin/local:$DOTFILES/bin
export PATH="$HOME/.cargo/bin:$PATH"
export WRKSP=$HOME/var
export WORK_DIR=$HOME/var
export EDITOR=micro

# load all config files
for file in $DOTFILES/dot/zsh/**/*.zsh
do
  source $file
done

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit

# load completions

## matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

## pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending
