# Finder preferences

Desktop: CDs Servers
New windows: Home
Folders: in tabs
Sidebar items: Applications Home Downloads Var iCloud External-CDs Servers
Advanced: o o x x x o o current
Cmd+j settings:
  - always open in list view
  - browse in list view
  - show library folder
