# Mac Mouse Fix preferences

Show in menu bar: yes
Scrolling: Precision
Buttons:
  Button 4 Click: Back
  Button 4 Double Click: Forward
  Button 4 Click and Scroll: Horizontal Scroll
  Button 4 Click and Drag: Scroll & Navigate
