gui:
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: "delta --dark --paging=never"
  skipHookPrefix: WIP
  autoFetch: false

os:
  editPreset: "micro"

promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true
