#! /usr/local/bin/python3
"""
Required brew packages:
    python
    git-standup (to report recent commits from the current directory)
"""

import subprocess

def ask(prompt):
    answer = None
    list = []
    while True:
        answer = input(prompt)
        if answer == "":
            break
        list.append(answer)
    return list

def format(emoji, list, emptyListString=None):
    if emptyListString and not list:
        return "%s\n" % (emptyListString)
    ret = ""
    for str in list:
        ret += "%s %s\n" % (emoji, str)
    return ret

# instructions
print("This tool can help you generate a standup report.")
print("Each question will repeat until a blank response is entered.")
print("Other emoji you may want to use are\n  :question: (for blockers that are questions)\n  :rocket: (for Pull Requests)\n  :small_blue_diamond: (for other notes)")
print("Here is a summary of your previous day's commits:")
subprocess.run(["git", "standup"])
print("----------")

# inputs
done    = ask("What have you done?     ")
working = ask("What are you doing now? ")
next    = ask("What will you do next?  ")
blocks  = ask("What is blocking you?   ")

# outputs
output = ""
output += format(":white_check_mark:", done)
output += format(":on:", working)
output += format(":soon:", next)
output += format(":no_entry_sign:", blocks, ":small_blue_diamond: No blocks")

subprocess.Popen(["pbcopy"], stdin=subprocess.PIPE).communicate(output.encode('utf-8'))

print("----------")
print("Below is your standup report.")
print("It has been copied to the clipboard, paste it into slack!")
print("----------")

print(output)
